import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { LocalArtifactStore } from "@athena/core"
import { DataScriptRunner, loadDirectory, packDirectory } from "../src/script_runner.js"
import { DataScriptBundleSchema } from "../src/contracts.js"

const shell = vi.hoisted(() => ({ run: vi.fn() }))
vi.mock("node:child_process", async () => {
  const { promisify } = await import("node:util")
  return { execFile: Object.assign(() => {}, { [promisify.custom]: shell.run }) }
})

let dir: string
beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "athena-script-"))
  shell.run.mockReset()
  shell.run.mockImplementation(async (_cmd, args, opts) => {
    if (args[0] === "lock") writeFileSync(join(opts.cwd, "uv.lock"), "locked dependencies")
    return { stdout: args.includes("--version") ? "Python 3.12.1\n" : "", stderr: "" }
  })
})
afterEach(() => rmSync(dir, { recursive: true, force: true }))

async function fixture() {
  const draft = join(dir, "draft")
  mkdirSync(draft)
  writeFileSync(join(draft, "evaluate.py"), "# evaluator")
  writeFileSync(join(draft, "labels.csv"), "id,label\n1,1")
  writeFileSync(join(draft, "pyproject.toml"), "[project]\nname = 'test'\nversion = '0.1.0'")
  const store = new LocalArtifactStore(join(dir, "artifacts"))
  const runner = new DataScriptRunner(store, join(dir, "runs"))
  const bundle = await runner.freeze(draft, "evaluate.py")
  return { store, runner, bundle, draft }
}

describe("data script runner", () => {
  it("freezes source, labels and dependency metadata with the shared command path", async () => {
    const { store, runner, bundle, draft } = await fixture()
    expect(runner).not.toHaveProperty("command")
    expect(bundle.python_version).toBe("3.12.1")
    expect(await store.getText(bundle.lock_ref!)).toBe("locked dependencies")
    const files = await loadDirectory(store, bundle.tree_ref!)
    expect(Object.keys(files)).toEqual(["evaluate.py", "labels.csv"])
    expect(Buffer.from(files["evaluate.py"]!).toString()).toBe("# ATHENA-FROZEN: do not edit this file\n# evaluator")
    expect(await store.getBytes(bundle.source_ref!)).toEqual(files["evaluate.py"])
    expect(shell.run.mock.calls.map(([command, args]) => [command, args])).toEqual([
      ["uv", ["lock"]], ["uv", ["run", "python", "--version"]],
    ])
    for (const [, , options] of shell.run.mock.calls) {
      expect(options).toMatchObject({ cwd: draft, timeout: 900000, encoding: "utf-8" })
    }
  })

  it.each(["file", "stdout"])("restores frozen files and returns direct output via %s", async (mode) => {
    const { store, runner, bundle } = await fixture()
    shell.run.mockReset().mockResolvedValueOnce({ stdout: "", stderr: "" })
    shell.run.mockImplementationOnce(async (command, args, options) => {
      expect(command).toBe("uv")
      expect(args.slice(0, 3)).toEqual(["run", "evaluate.py", "--request"])
      expect(JSON.parse(readFileSync(args[3], "utf-8"))).toEqual({ task: "score" })
      expect(readFileSync(join(options.cwd, "predictions", "values.csv"), "utf-8")).toBe("prediction")
      expect(readFileSync(join(options.cwd, "labels.csv"), "utf-8")).toContain("label")
      if (mode === "file") writeFileSync(args[5], '{"primary":0.8}')
      return { stdout: mode === "file" ? "ignored" : 'log line\n{"primary":0.8}\n', stderr: "" }
    })
    const put = vi.spyOn(store, "putText")
    const result = await runner.run(bundle, { task: "score" }, { primary: null }, {
      "predictions/values.csv": Buffer.from("prediction"),
    })
    expect(result).toEqual({ primary: 0.8 })
    expect(put).not.toHaveBeenCalled()
    expect(shell.run.mock.calls[0]![1]).toEqual(["sync"])
  })

  it("rejects missing required output fields", async () => {
    const { runner, bundle } = await fixture()
    shell.run.mockResolvedValue({ stdout: "{}", stderr: "" })
    await expect(runner.run(bundle, {}, { primary: null })).rejects.toThrow("missing schema fields")
  })

  it("rejects unfrozen bundles before invoking subprocesses", async () => {
    const store = new LocalArtifactStore(join(dir, "artifacts"))
    const runner = new DataScriptRunner(store, join(dir, "runs"))
    await expect(runner.run(DataScriptBundleSchema.parse({ bundle_id: "b", entrypoint: "eval.py" }), {})).rejects.toThrow("not frozen")
    expect(shell.run).not.toHaveBeenCalled()
  })

  it("round-trips nested binary directory contents", async () => {
    const root = join(dir, "files")
    mkdirSync(join(root, "nested"), { recursive: true })
    writeFileSync(join(root, "nested", "data.bin"), Buffer.from([0, 255, 128]))
    const store = new LocalArtifactStore(join(dir, "artifacts"))
    expect(await loadDirectory(store, await packDirectory(store, root))).toEqual({
      "nested/data.bin": Buffer.from([0, 255, 128]),
    })
  })
})
