"""DataScriptRunner — python-uv 数据脚本 Bundle 生命周期（supervisor_imp_docs Task 4）。

LLM 生成的数据脚本以 Bundle 形式冻结：DRAFT 允许 ``uv init/uv add/uv run``；冻结时
``uv lock`` 并把源码/pyproject.toml/uv.lock 固化到 ArtifactStore，并在 entrypoint
文件头部写「不能动」冻结标记（取代脆弱的 ``uv --frozen`` 锁定）。统一调用合同：

    uv run <declared-entrypoint> --request <request.json> --output <result.json>

Runner 不按脚本文件名寻找入口，只认 Bundle metadata 声明的 entrypoint。
"""

import asyncio
import hashlib
import json
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from athena.core.contracts import ArtifactRef, ArtifactStore, new_id
from athena.research.contracts import DataScriptBundle


@dataclass
class BundleMetadata:
    """冻结 Bundle 的声明式 metadata（唯一 entrypoint + 说明）。"""

    entrypoint: str
    description: str = ""


@dataclass
class ScriptRunResult:
    """一次冻结 bundle 运行的结果（首版 strong_isolation=false）。"""

    result_refs: list[str] = field(default_factory=list)
    outputs: dict[str, object] = field(default_factory=dict)
    strong_isolation: bool = False


# 确定性 runner 的固定命令超时（秒）：防止冻结/评估脚本卡死无限挂起。
# TODO(supervisor-security): 强隔离 runner 落地后，本地 workspace shell 语义随之替换。
_COMMAND_TIMEOUT_S = 900

# 冻结标记：freeze 时写入 entrypoint 文件头部，标识其为冻结产物、不可再编辑。
# 取代 uv --frozen 的强制锁定——--frozen 依赖 uv.lock 与 pyproject 严格同步，
# 锁文件稍有出入就报 non-zero exit，冻结反而脆弱。
_FROZEN_HEADER = "# ATHENA-FROZEN: do not edit this file\n"


class ScriptCommandError(subprocess.CalledProcessError):
    """``CalledProcessError``，但消息里带上被捕获的 stderr。

    默认的 ``str()`` 只有 "Command '[...]' returned non-zero exit status 1"，而这些
    失败最终是要变成 Agent 修复反馈的——退出码说不出该改什么。真机（2026-08-16 A/B
    的 survey-on 臂）：评估器明明在 stderr 写了 ``4800 prediction ids not in labels``，
    传到 PREPARE 的却只有退出码，于是它重试 11 次、每次交出同样的 6000 行预测，直到
    轮次预算耗尽。stderr 里那一行正是"预测只该覆盖留出的那批 id"。

    仍是 ``CalledProcessError`` 子类，既有的 ``SubprocessError`` 捕获点不受影响。
    """

    def __str__(self) -> str:
        detail = " ".join((self.stderr or "").split())[:600]
        return f"{super().__str__()}: {detail}" if detail else super().__str__()


def _run(cmd: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    """以统一超时/捕获策略运行命令，失败抛 ``ScriptCommandError``（含 stderr）。

    超时用 ``TimeoutExpired``（``SubprocessError`` 子类）而非 ``RuntimeError``，
    这样上层 PREPARE 重试元组能按「可重试」捕获，而不是误判成终态。
    """
    completed = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=_COMMAND_TIMEOUT_S,
    )
    if completed.returncode:
        raise ScriptCommandError(
            completed.returncode, cmd, completed.stdout, completed.stderr
        )
    return completed


def _run_cmd(cmd: list[str], *, cwd: Path) -> None:
    """在给定目录运行命令，丢弃输出。"""
    _run(cmd, cwd=cwd)


def _run_cmd_capture(cmd: list[str], *, cwd: Path) -> str:
    """在给定目录运行命令并返回 stdout（去空白）。"""
    return _run(cmd, cwd=cwd).stdout.strip()


def _validate_schema(payload: dict[str, object], schema: dict[str, object]) -> None:
    """校验 output.json 命中声明字段；缺字段报错（类型检查首版宽松）。"""
    missing = [key for key in schema if key not in payload]
    if missing:
        raise RuntimeError(f"bundle output missing schema fields: {missing}")


async def pack_directory(store: ArtifactStore, root: Path) -> ArtifactRef:
    """把 root 目录整树存为清单 artifact；返回指向清单 JSON 的 ref。

    复用 freeze 的 tree 模式：遍历 root.rglob("*") 的文件，逐文件 store.put_bytes，
    得到 {"<相对路径>": <bytes_ref>}，再 store.put_text(json.dumps(...)) 返回清单 ref。
    相对路径用 path.relative_to(root).as_posix()。
    """
    tree: dict[str, str] = {}
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root).as_posix()
        tree[rel] = await store.put_bytes(path.read_bytes())
    return await store.put_text(json.dumps(tree, ensure_ascii=False))


async def load_directory(store: ArtifactStore, ref: ArtifactRef) -> dict[str, bytes]:
    """从 pack_directory 的清单 ref 读回 {相对路径: bytes}。"""
    tree = json.loads(await store.get_text(ref))
    return {
        rel: await store.get_bytes(content_ref) for rel, content_ref in tree.items()
    }


def _read_output(output_path: Path, stdout: str) -> dict[str, object]:
    """读取 eval 输出：优先 result.json，否则解析 stdout 末行 JSON。

    兼容两种 eval 合同——旧式 ``--output`` 写 result.json，新式 metric.json 的
    eval 脚本直接打印一行 ``{"primary": <float>}`` 到 stdout（不写文件）。
    """
    if output_path.is_file():
        return json.loads(output_path.read_text(encoding="utf-8"))
    lines = [line for line in stdout.splitlines() if line.strip()]
    if not lines:
        raise RuntimeError("bundle produced no result.json or stdout output")
    try:
        return json.loads(lines[-1])
    except ValueError:
        raise RuntimeError("bundle produced no parseable eval output") from None


class DataScriptRunner:
    """python-uv Bundle 的 DRAFT/FROZEN 生命周期与统一 CLI+JSON 执行。"""

    def __init__(self, *, store: ArtifactStore, workdir: Path) -> None:
        self._store = store
        self._workdir = Path(workdir)

    def command(
        self,
        bundle: DataScriptBundle,
        request_path: str = "request.json",
        output_path: str = "result.json",
    ) -> list[str]:
        """构造冻结 bundle 的统一执行命令（uv run，不再 --frozen）。"""
        return [
            "uv",
            "run",
            bundle.entrypoint,
            "--request",
            request_path,
            "--output",
            output_path,
        ]

    async def freeze(
        self, workspace: Path, metadata: BundleMetadata
    ) -> DataScriptBundle:
        """冻结 draft：uv lock + 固化完整源码树/Python 版本/environment hash。

        只允许之后的 ``uv sync --frozen`` 与 ``uv run --frozen``。
        """
        ws = Path(workspace)
        entrypoint = metadata.entrypoint
        if not (ws / entrypoint).is_file():
            raise FileNotFoundError(f"declared entrypoint missing: {entrypoint}")
        if not (ws / "pyproject.toml").is_file():
            raise FileNotFoundError(
                f"draft must be a uv project with pyproject.toml "
                f"(missing {ws / 'pyproject.toml'})"
            )
        project_text = (ws / "pyproject.toml").read_text(encoding="utf-8")
        # 1. 完整源码树（排除 pyproject/uv.lock/.venv，另存）；entrypoint 写入冻结标记。
        tree: dict[str, str] = {}
        for path in sorted(ws.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(ws).as_posix()
            if rel in ("pyproject.toml", "uv.lock") or rel.startswith(".venv/"):
                continue
            content = path.read_bytes()
            if rel == entrypoint:
                content = _FROZEN_HEADER.encode("utf-8") + content
            tree[rel] = await self._store.put_bytes(content)
        tree_ref = await self._store.put_text(json.dumps(tree, ensure_ascii=False))
        # TODO(supervisor-security): 完整流程跑通后，用强隔离 runner 替换本地 workspace shell；生产/敏感数据发布前必须完成。
        await asyncio.to_thread(_run_cmd, ["uv", "lock"], cwd=ws)
        lock_text = (ws / "uv.lock").read_text(encoding="utf-8")
        # 2. 解析出的解释器版本 + environment hash
        py_version = await asyncio.to_thread(
            _run_cmd_capture,
            ["uv", "run", "python", "--version"],
            cwd=ws,
        )
        py_version = py_version.removeprefix("Python ").strip()
        env_hash = hashlib.sha256(
            (project_text + lock_text + py_version).encode("utf-8")
        ).hexdigest()
        lock_ref = await self._store.put_text(lock_text)
        project_ref = await self._store.put_text(project_text)
        source_ref = await self._store.put_bytes(
            _FROZEN_HEADER.encode("utf-8") + (ws / entrypoint).read_bytes()
        )
        return DataScriptBundle(
            bundle_id=new_id("bundle"),
            entrypoint=entrypoint,
            runtime="python-uv",
            lock_ref=lock_ref,
            project_ref=project_ref,
            source_ref=source_ref,
            tree_ref=tree_ref,
            python_version=py_version,
            environment_hash=env_hash,
        )

    async def run(
        self,
        bundle: DataScriptBundle,
        request: dict[str, object],
        output_schema: dict[str, object] | None = None,
        *,
        extra_files: dict[str, bytes] | None = None,
    ) -> ScriptRunResult:
        """执行冻结 bundle；重建冻结项目上下文并读取/校验 output.json。

        在隔离工作目录重建完整源码树 + pyproject.toml + uv.lock 后，先
        ``uv sync --frozen`` 再 ``uv run --frozen`` 执行（只允许这两个 FROZEN 命令）。
        ``extra_files`` 注入相对路径字节文件（如 predictions 目录树/labels），
        供 trusted evaluator 在对齐后运行 eval 入口。
        """
        if (
            bundle.project_ref is None
            or bundle.lock_ref is None
            or bundle.tree_ref is None
        ):
            raise RuntimeError("bundle is not frozen (missing project/lock/tree refs)")
        self._workdir.mkdir(parents=True, exist_ok=True)
        run_dir = Path(tempfile.mkdtemp(prefix="athena-script-run-", dir=self._workdir))
        (run_dir / "pyproject.toml").write_text(
            await self._store.get_text(bundle.project_ref), encoding="utf-8"
        )
        (run_dir / "uv.lock").write_text(
            await self._store.get_text(bundle.lock_ref), encoding="utf-8"
        )
        tree = json.loads(await self._store.get_text(bundle.tree_ref))
        for rel, content_ref in tree.items():
            target = run_dir / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(await self._store.get_bytes(content_ref))
        for rel, content in (extra_files or {}).items():
            target = run_dir / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
        request_path = run_dir / "request.json"
        output_path = run_dir / "result.json"
        request_path.write_text(
            json.dumps(request, ensure_ascii=False), encoding="utf-8"
        )
        # TODO(supervisor-security): 同上——本地 workspace shell 仅首版原型。
        await asyncio.to_thread(_run_cmd, ["uv", "sync"], cwd=run_dir)
        cmd = self.command(bundle, str(request_path), str(output_path))
        stdout = await asyncio.to_thread(_run_cmd_capture, cmd, cwd=run_dir)
        payload = _read_output(output_path, stdout)
        if output_schema is not None:
            _validate_schema(payload, output_schema)
        result_ref = await self._store.put_text(json.dumps(payload, ensure_ascii=False))
        return ScriptRunResult(
            result_refs=[result_ref],
            outputs=payload,
            strong_isolation=False,
        )
