import {
  Activity,
  Atom,
  BookOpen,
  Box,
  Brain,
  Bug,
  Calculator,
  ChartColumn,
  ChartLine,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  Columns3,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileCode2,
  FileDiff,
  FileText,
  Filter,
  FlaskConical,
  FolderOpen,
  FolderTree,
  Gauge,
  GitBranch,
  Globe,
  Hammer,
  History,
  Info,
  KeyRound,
  Layers,
  Lightbulb,
  List,
  Loader2,
  Lock,
  MessageCircle,
  MessagesSquare,
  Microscope,
  Moon,
  Network,
  PanelLeft,
  PanelLeftClose,
  Pause,
  Play,
  RefreshCw,
  Rocket,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sigma,
  Sparkles,
  SquareTerminal,
  Star,
  Sun,
  Table,
  Target,
  Trash2,
  Trophy,
  Upload,
  Users,
  Variable,
  Wallet,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Semantic icon registry: name → Lucide SVG component. */
const ICONS = {
  metrics: ChartLine,
  tree: GitBranch,
  network: Network,
  algorithms: Calculator,
  experiments: FlaskConical,
  llm: MessagesSquare,
  settings: Settings,
  search: Search,
  wallet: Wallet,
  trophy: Trophy,
  report: FileText,
  sun: Sun,
  moon: Moon,
  sparkles: Sparkles,
  wrench: Wrench,
  diff: FileDiff,
  files: FolderTree,
  folder: FolderOpen,
  log: ScrollText,
  send: Send,
  loader: Loader2,
  chat: MessageCircle,
  chart: ChartColumn,
  clock: Clock,
  close: X,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  panelLeft: PanelLeft,
  panelLeftClose: PanelLeftClose,
  trash: Trash2,
  // 扩展图标：数据、工具、状态与通用语义
  activity: Activity,
  atom: Atom,
  book: BookOpen,
  box: Box,
  brain: Brain,
  bug: Bug,
  clipboard: ClipboardList,
  columns: Columns3,
  database: Database,
  download: Download,
  external: ExternalLink,
  eye: Eye,
  fileCode: FileCode2,
  filter: Filter,
  gauge: Gauge,
  globe: Globe,
  hammer: Hammer,
  history: History,
  info: Info,
  key: KeyRound,
  layers: Layers,
  lightbulb: Lightbulb,
  list: List,
  lock: Lock,
  microscope: Microscope,
  pause: Pause,
  play: Play,
  refresh: RefreshCw,
  rocket: Rocket,
  shield: ShieldCheck,
  sigma: Sigma,
  squareTerminal: SquareTerminal,
  star: Star,
  table: Table,
  target: Target,
  upload: Upload,
  users: Users,
  variable: Variable,
  webhook: Webhook,
  workflow: Workflow,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
}

/** Crisp, consistent SVG icon (replaces emoji for cross-platform fidelity). */
export function Icon({ name, size = 16, className }: IconProps) {
  const Component: LucideIcon = ICONS[name];
  return <Component size={size} className={className} />;
}
