/**
 * DataScriptRunner — python-uv 数据脚本 Bundle 生命周期（移植 ``research/script_runner.py``）。
 */

import { createHash } from "node:crypto"
import { execFile } from "node:child_process"
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs"
import { join, relative, sep } from "node:path"
import { promisify } from "node:util"

import { newId, type ArtifactRef, type ArtifactStore } from "@athena/core"

import { DataScriptBundleSchema, type DataScriptBundle } from "./contracts.js"

const execFileP = promisify(execFile)

/** 冻结 Bundle 的声明式 metadata。 */
export class BundleMetadata {
  constructor(
    public readonly entrypoint: string,
    public readonly description: string = ""
  ) {}
}

/** 一次冻结 bundle 运行的结果（首版 strong_isolation=false）。 */
export class ScriptRunResult {
  constructor(
    public readonly resultRefs: string[] = [],
    public readonly outputs: Record<string, unknown> = {},
    public readonly strongIsolation: boolean = false
  ) {}
}

const COMMAND_TIMEOUT_S = 900
const FROZEN_HEADER = "# ATHENA-FROZEN: do not edit this file\n"

function walkFiles(dir: string, base: string = dir): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walkFiles(full, base))
    else if (entry.isFile()) out.push(relative(base, full).split(sep).join("/"))
  }
  return out.sort()
}

async function runCmd(cmd: string[], cwd: string): Promise<void> {
  await execFileP(cmd[0]!, cmd.slice(1), {
    cwd,
    maxBuffer: 100 * 1024 * 1024,
    timeout: COMMAND_TIMEOUT_S * 1000,
  })
}

async function runCmdCapture(cmd: string[], cwd: string): Promise<string> {
  const { stdout } = await execFileP(cmd[0]!, cmd.slice(1), {
    cwd,
    maxBuffer: 100 * 1024 * 1024,
    timeout: COMMAND_TIMEOUT_S * 1000,
    encoding: "utf-8",
  })
  return String(stdout).trim()
}

function validateSchema(payload: Record<string, unknown>, schema: Record<string, unknown>): void {
  const missing = Object.keys(schema).filter((key) => !(key in payload))
  if (missing.length) {
    throw new Error(`bundle output missing schema fields: ${missing}`)
  }
}

function readOutput(outputPath: string, stdout: string): Record<string, unknown> {
  if (existsSync(outputPath)) {
    return JSON.parse(readFileSync(outputPath, "utf-8"))
  }
  const lines = stdout.split(/\r?\n/).filter((line) => line.trim())
  if (lines.length === 0) {
    throw new Error("bundle produced no result.json or stdout output")
  }
  try {
    return JSON.parse(lines[lines.length - 1]!)
  } catch {
    throw new Error("bundle produced no parseable eval output")
  }
}

/** 把 root 目录整树存为清单 artifact；返回指向清单 JSON 的 ref。 */
export async function packDirectory(store: ArtifactStore, root: string): Promise<ArtifactRef> {
  const tree: Record<string, string> = {}
  for (const rel of walkFiles(root)) {
    tree[rel] = await store.putBytes(readFileSync(join(root, rel)))
  }
  return store.putText(JSON.stringify(tree))
}

/** 从 pack_directory 的清单 ref 读回 {相对路径: bytes}。 */
export async function loadDirectory(
  store: ArtifactStore,
  ref: ArtifactRef
): Promise<Record<string, Uint8Array>> {
  const tree = JSON.parse(await store.getText(ref)) as Record<string, string>
  const out: Record<string, Uint8Array> = {}
  for (const [rel, contentRef] of Object.entries(tree)) {
    out[rel] = await store.getBytes(contentRef)
  }
  return out
}

export class DataScriptRunner {
  private store: ArtifactStore
  private workdir: string

  constructor(store: ArtifactStore, workdir: string) {
    this.store = store
    this.workdir = workdir
  }

  /** 构造冻结 bundle 的统一执行命令（uv run）。 */
  command(
    bundle: DataScriptBundle,
    requestPath = "request.json",
    outputPath = "result.json"
  ): string[] {
    return [
      "uv",
      "run",
      bundle.entrypoint,
      "--request",
      requestPath,
      "--output",
      outputPath,
    ]
  }

  /** 冻结 draft：uv lock + 固化完整源码树/Python 版本/environment hash。 */
  async freeze(workspace: string, metadata: BundleMetadata): Promise<DataScriptBundle> {
    const ws = workspace
    const entrypoint = metadata.entrypoint
    if (!existsSync(join(ws, entrypoint))) {
      throw new Error(`declared entrypoint missing: ${entrypoint}`)
    }
    if (!existsSync(join(ws, "pyproject.toml"))) {
      throw new Error(
        `draft must be a uv project with pyproject.toml (missing ${join(ws, "pyproject.toml")})`
      )
    }
    const projectText = readFileSync(join(ws, "pyproject.toml"), "utf-8")

    const tree: Record<string, string> = {}
    for (const rel of walkFiles(ws)) {
      if (rel === "pyproject.toml" || rel === "uv.lock" || rel.startsWith(".venv/")) continue
      let content = readFileSync(join(ws, rel))
      if (rel === entrypoint) content = Buffer.concat([Buffer.from(FROZEN_HEADER), content])
      tree[rel] = await this.store.putBytes(content)
    }
    const treeRef = await this.store.putText(JSON.stringify(tree))

    // TODO(supervisor-security): 完整流程跑通后，用强隔离 runner 替换本地 workspace shell。
    await runCmd(["uv", "lock"], ws)
    const lockText = readFileSync(join(ws, "uv.lock"), "utf-8")
    const pyVersion = (await runCmdCapture(["uv", "run", "python", "--version"], ws))
      .replace(/^Python\s+/, "")
      .trim()
    const envHash = createHash("sha256")
      .update(projectText + lockText + pyVersion)
      .digest("hex")
    const lockRef = await this.store.putText(lockText)
    const projectRef = await this.store.putText(projectText)
    const sourceRef = await this.store.putBytes(
      Buffer.concat([Buffer.from(FROZEN_HEADER), readFileSync(join(ws, entrypoint))])
    )

    return DataScriptBundleSchema.parse({
      bundle_id: newId("bundle"),
      entrypoint,
      runtime: "python-uv",
      lock_ref: lockRef,
      project_ref: projectRef,
      source_ref: sourceRef,
      tree_ref: treeRef,
      python_version: pyVersion,
      environment_hash: envHash,
    })
  }

  /** 执行冻结 bundle；重建冻结项目上下文并读取/校验 output.json。 */
  async run(
    bundle: DataScriptBundle,
    request: Record<string, unknown>,
    outputSchema: Record<string, unknown> | null = null,
    extraFiles: Record<string, Uint8Array> | null = null
  ): Promise<ScriptRunResult> {
    if (bundle.project_ref === null || bundle.lock_ref === null || bundle.tree_ref === null) {
      throw new Error("bundle is not frozen (missing project/lock/tree refs)")
    }
    mkdirSync(this.workdir, { recursive: true })
    const runDir = mkdtempSync(join(this.workdir, "athena-script-run-"))
    writeFileSync(join(runDir, "pyproject.toml"), await this.store.getText(bundle.project_ref), "utf-8")
    writeFileSync(join(runDir, "uv.lock"), await this.store.getText(bundle.lock_ref), "utf-8")
    const tree = JSON.parse(await this.store.getText(bundle.tree_ref)) as Record<string, string>
    for (const [rel, contentRef] of Object.entries(tree)) {
      const target = join(runDir, rel)
      mkdirSync(join(target, ".."), { recursive: true })
      writeFileSync(target, await this.store.getBytes(contentRef))
    }
    for (const [rel, content] of Object.entries(extraFiles ?? {})) {
      const target = join(runDir, rel)
      mkdirSync(join(target, ".."), { recursive: true })
      writeFileSync(target, content)
    }
    const requestPath = join(runDir, "request.json")
    const outputPath = join(runDir, "result.json")
    writeFileSync(requestPath, JSON.stringify(request), "utf-8")

    // TODO(supervisor-security): 本地 workspace shell 仅首版原型。
    await runCmd(["uv", "sync"], runDir)
    const cmd = this.command(bundle, requestPath, outputPath)
    const stdout = await runCmdCapture(cmd, runDir)
    const payload = readOutput(outputPath, stdout)
    if (outputSchema !== null) validateSchema(payload, outputSchema)
    const resultRef = await this.store.putText(JSON.stringify(payload))
    return new ScriptRunResult([resultRef], payload, false)
  }
}
