/**
 * DataScriptRunner — python-uv 数据脚本 Bundle 生命周期（移植 ``research/script_runner.py``）。
 */

import { createHash } from "node:crypto"
import { execFile } from "node:child_process"
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs"
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path"
import { promisify } from "node:util"

import { newId, type ArtifactRef, type ArtifactStore } from "@athena/core"

import { DataScriptBundleSchema, type DataScriptBundle } from "./contracts.js"

const execFileP = promisify(execFile)

const COMMAND_TIMEOUT_S = 900
const FROZEN_HEADER = "# ATHENA-FROZEN: do not edit this file\n"

function walkFiles(root: string, excluded: readonly string[] = []): string[] {
  const out: string[] = []
  function visit(dir: string) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name)
      const rel = relative(root, full).split(sep).join("/")
      if (excluded.includes(rel)) continue
      if (entry.isDirectory()) visit(full)
      else if (entry.isFile()) out.push(rel)
    }
  }
  visit(root)
  return out.sort()
}

function localPath(root: string, rel: string): string {
  const target = resolve(root, rel)
  const path = relative(root, target)
  if (!path || isAbsolute(rel) || isAbsolute(path) || path === ".." || path.startsWith(`..${sep}`)) {
    throw new Error(`bundle path must stay inside its directory: ${rel}`)
  }
  return target
}

async function runCmd(cmd: string[], cwd: string): Promise<string> {
  const { stdout } = await execFileP(cmd[0]!, cmd.slice(1), {
    cwd,
    maxBuffer: 100 * 1024 * 1024,
    timeout: COMMAND_TIMEOUT_S * 1000,
    encoding: "utf-8",
  })
  return String(stdout).trim()
}

function readOutput(outputPath: string, stdout: string): Record<string, unknown> {
  const text = existsSync(outputPath)
    ? readFileSync(outputPath, "utf-8")
    : stdout.split(/\r?\n/).filter((line) => line.trim()).at(-1)
  if (text === undefined) {
    throw new Error("bundle produced no result.json or stdout output")
  }
  let payload: unknown
  try {
    payload = JSON.parse(text)
  } catch {
    throw new Error("bundle produced no parseable eval output")
  }
  if (payload === null || typeof payload !== "object" || Array.isArray(payload)) {
    throw new Error("bundle output must be a JSON object")
  }
  return payload as Record<string, unknown>
}

/** 把 root 目录整树存为清单 artifact；返回指向清单 JSON 的 ref。 */
export async function packDirectory(store: ArtifactStore, root: string): Promise<ArtifactRef> {
  const tree: Record<string, string> = {}
  for (const rel of walkFiles(root)) {
    tree[rel] = await store.putBytes(readFileSync(join(root, rel)))
  }
  return store.putText(JSON.stringify(tree))
}

/** 从 pack_directory 的清单 ref 读回 {相对路径: bytes}。 */
export async function loadDirectory(
  store: ArtifactStore,
  ref: ArtifactRef
): Promise<Record<string, Uint8Array>> {
  const tree = JSON.parse(await store.getText(ref)) as Record<string, string>
  const out: Record<string, Uint8Array> = {}
  for (const [rel, contentRef] of Object.entries(tree)) {
    out[rel] = await store.getBytes(contentRef)
  }
  return out
}

export class DataScriptRunner {
  constructor(private readonly store: ArtifactStore, private readonly workdir: string) {}

  /** 冻结 draft：uv lock + 固化完整源码树/Python 版本/environment hash。 */
  async freeze(ws: string, entrypoint: string): Promise<DataScriptBundle> {
    entrypoint = relative(ws, localPath(ws, entrypoint)).split(sep).join("/")
    const files = walkFiles(ws, ["pyproject.toml", "uv.lock", ".venv", "request.json", "result.json"])
    if (!files.includes(entrypoint)) {
      throw new Error(`declared entrypoint missing: ${entrypoint}`)
    }
    if (!existsSync(join(ws, "pyproject.toml"))) {
      throw new Error(
        `draft must be a uv project with pyproject.toml (missing ${join(ws, "pyproject.toml")})`
      )
    }
    const projectText = readFileSync(join(ws, "pyproject.toml"), "utf-8")

    const tree: Record<string, string> = {}
    for (const rel of files) {
      let content = readFileSync(join(ws, rel))
      if (rel === entrypoint) content = Buffer.concat([Buffer.from(FROZEN_HEADER), content])
      tree[rel] = await this.store.putBytes(content)
    }
    const treeRef = await this.store.putText(JSON.stringify(tree))

    // TODO(supervisor-security): 完整流程跑通后，用强隔离 runner 替换本地 workspace shell。
    await runCmd(["uv", "lock"], ws)
    const lockText = readFileSync(join(ws, "uv.lock"), "utf-8")
    const pyVersion = (await runCmd(["uv", "run", "python", "--version"], ws))
      .replace(/^Python\s+/, "")
      .trim()
    const envHash = createHash("sha256")
      .update(projectText + lockText + pyVersion)
      .digest("hex")
    const lockRef = await this.store.putText(lockText)
    const projectRef = await this.store.putText(projectText)

    return DataScriptBundleSchema.parse({
      bundle_id: newId("bundle"),
      entrypoint,
      runtime: "python-uv",
      lock_ref: lockRef,
      project_ref: projectRef,
      source_ref: tree[entrypoint],
      tree_ref: treeRef,
      python_version: pyVersion,
      environment_hash: envHash,
    })
  }

  /** 重建冻结项目并注入附加文件；评分策略由 TrustedEvaluator 负责。 */
  async run(
    bundle: DataScriptBundle,
    extraFiles: Record<string, Uint8Array> = {}
  ): Promise<Record<string, unknown>> {
    if (bundle.project_ref === null || bundle.lock_ref === null || bundle.tree_ref === null) {
      throw new Error("bundle is not frozen (missing project/lock/tree refs)")
    }
    mkdirSync(this.workdir, { recursive: true })
    const runDir = mkdtempSync(join(this.workdir, "athena-script-run-"))
    localPath(runDir, bundle.entrypoint)
    writeFileSync(join(runDir, "pyproject.toml"), await this.store.getText(bundle.project_ref), "utf-8")
    writeFileSync(join(runDir, "uv.lock"), await this.store.getText(bundle.lock_ref), "utf-8")
    const requestPath = join(runDir, "request.json")
    const outputPath = join(runDir, "result.json")
    writeFileSync(requestPath, "{}", "utf-8")
    for (const files of [await loadDirectory(this.store, bundle.tree_ref), extraFiles]) {
      for (const [rel, content] of Object.entries(files)) {
        const target = localPath(runDir, rel)
        if (relative(runDir, target).toLowerCase() === "result.json") {
          throw new Error("result.json is reserved for evaluator output")
        }
        mkdirSync(dirname(target), { recursive: true })
        writeFileSync(target, content, { flag: "wx" })
      }
    }

    // TODO(supervisor-security): 本地 workspace shell 仅首版原型。
    await runCmd(["uv", "sync"], runDir)
    const stdout = await runCmd(["uv", "run", bundle.entrypoint, "--request", requestPath, "--output", outputPath], runDir)
    return readOutput(outputPath, stdout)
  }
}
