import { appendFileSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { StageContext } from "../core/pipeline-types.js"

export interface PaperDir {
  root: string
  draftPath: string
  draftRef: string
}

export interface ComposeResult extends PaperDir {
  sections: string[]
}

export class PaperComposer {
  async compose(ctx: StageContext): Promise<ComposeResult> {
    const root = paperRoot(ctx)
    const sectionsDir = join(root, "sections")
    mkdirSync(sectionsDir, { recursive: true })

    const title = String(ctx.state.paper_spec.title ?? "Untitled AutoResearch")
    const abstract = String(ctx.state.paper_spec.abstract ?? "")
    const sectionNames = [
      "introduction",
      "related_work",
      "method",
      "experiments",
      "results",
      "limitations",
      "conclusion",
    ]

    for (const name of sectionNames) {
      writeFileSync(join(sectionsDir, `${name}.tex`), `\\section{${name.replaceAll("_", " ")}}
% TODO: generated by PaperComposer
`)
    }

    const draft = [
      `# ${title}`,
      "",
      abstract ? `> ${abstract}` : "",
      "",
      ...sectionNames.map((name) => `## ${name.replaceAll("_", " ")}`),
      "",
    ].join("\n")
    const draftPath = join(root, "paper_draft.md")
    writeFileSync(draftPath, draft)
    const draftRef = await ctx.artifacts.putText(draft)

    return { root, draftPath, draftRef, sections: sectionNames }
  }

  async revise(ctx: StageContext, paperDir: PaperDir, feedback: string[]): Promise<void> {
    const notes = feedback.length > 0 ? `\n## Revision Notes\n\n${feedback.map((item) => `- ${item}`).join("\n")}\n` : ""
    appendFileSync(paperDir.draftPath, notes)
    await ctx.artifacts.putText(notes)
  }

  async reviseLatex(ctx: StageContext, paperDir: PaperDir, logText: string): Promise<void> {
    const logPath = join(paperDir.root, "compile_feedback.md")
    writeFileSync(logPath, `\`\`\`text\n${logText}\n\`\`\`\n`)
    await ctx.artifacts.putText(logText)
  }
}

export function paperRoot(ctx: StageContext): string {
  return join(ctx.projectRoot, ".athena", "autoresearch", "paper", ctx.runId)
}
